"""fix: relación curso-certificado

Revision ID: 070e6cddb6bb
Revises: 7764a5d17131
Create Date: 2025-06-01 00:56:00.323324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070e6cddb6bb'
down_revision = '7764a5d17131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificados', schema=None) as batch_op:
        batch_op.alter_column('emisor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('correo_destino',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('curso_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('certificados_participante_id_fkey'), type_='foreignkey')
        batch_op.drop_column('participante_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participante_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('certificados_participante_id_fkey'), 'participantes', ['participante_id'], ['id'])
        batch_op.alter_column('curso_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('correo_destino',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('emisor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
