"""Agregar correo_destino a certificados

Revision ID: 07647638089c
Revises: d9b0aefba00d
Create Date: 2025-05-31 14:22:08.525160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07647638089c'
down_revision = 'd9b0aefba00d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_descarga', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('expira_en', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('descargado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('correo_destino', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['token_descarga'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificados', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('correo_destino')
        batch_op.drop_column('descargado')
        batch_op.drop_column('expira_en')
        batch_op.drop_column('token_descarga')

    # ### end Alembic commands ###
