"""fix: FK participante_id en certificado

Revision ID: 195363248288
Revises: 070e6cddb6bb
Create Date: 2025-06-01 00:58:29.246038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195363248288'
down_revision = '070e6cddb6bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participante_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'participantes', ['participante_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificados', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('participante_id')

    # ### end Alembic commands ###
