"""Crear tablas curso y participante

Revision ID: 7764a5d17131
Revises: a038f5d200ca
Create Date: 2025-05-31 23:41:34.794767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7764a5d17131'
down_revision = 'a038f5d200ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('duracion_horas', sa.Integer(), nullable=False),
    sa.Column('responsable_firma', sa.String(length=100), nullable=False),
    sa.Column('cargo_responsable', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=12), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('foto_nombre', sa.String(length=200), nullable=True),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('curso_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('participante_id', sa.Integer(), nullable=False))
        batch_op.alter_column('correo_destino',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('emisor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'participantes', ['participante_id'], ['id'])
        batch_op.create_foreign_key(None, 'cursos', ['curso_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificados', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('emisor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('correo_destino',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('participante_id')
        batch_op.drop_column('curso_id')

    op.drop_table('participantes')
    op.drop_table('cursos')
    # ### end Alembic commands ###
