"""Actualiza modelo Certificado con fecha_descarga e ip_descarga

Revision ID: a038f5d200ca
Revises: 07647638089c
Create Date: 2025-05-31 15:03:04.858749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a038f5d200ca'
down_revision = '07647638089c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_descarga', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ip_descarga', sa.String(length=45), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificados', schema=None) as batch_op:
        batch_op.drop_column('ip_descarga')
        batch_op.drop_column('fecha_descarga')

    # ### end Alembic commands ###
