"""relación N:M participante-curso

Revision ID: d53c80159737
Revises: 075d7c877b01
Create Date: 2025-06-08 16:08:02.999460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53c80159737'
down_revision = '075d7c877b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=512), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('participantes_cursos',
    sa.Column('participante_id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], ),
    sa.PrimaryKeyConstraint('participante_id', 'curso_id')
    )
    op.drop_table('usuario')
    with op.batch_alter_table('certificados', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['emisor_id'], ['id'])

    with op.batch_alter_table('participantes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('participantes_curso_id_fkey'), type_='foreignkey')
        batch_op.drop_column('curso_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('curso_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('participantes_curso_id_fkey'), 'cursos', ['curso_id'], ['id'])

    with op.batch_alter_table('certificados', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_completo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('correo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('contrasena_hash', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('rol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usuario_pkey')),
    sa.UniqueConstraint('correo', name=op.f('usuario_correo_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('participantes_cursos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
