"""tabla certificados

Revision ID: f0736617dc2b
Revises: a3014d0a418b
Create Date: 2025-05-29 12:15:06.574248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0736617dc2b'
down_revision = 'a3014d0a418b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_participante', sa.String(length=100), nullable=False),
    sa.Column('nombre_evento', sa.String(length=150), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=True),
    sa.Column('duracion_horas', sa.Integer(), nullable=True),
    sa.Column('archivo_nombre', sa.String(length=200), nullable=True),
    sa.Column('archivo_hash', sa.String(length=64), nullable=True),
    sa.Column('emisor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emisor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('archivo_hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificados')
    # ### end Alembic commands ###
